export const carModel=[
  {
    "city_mpg": 23,
    "class": "compact car",
    "combination_mpg": 24,
    "cylinders": 4,
    "displacement": 1.6,
    "drive": "fwd",
    "fuel_type": "gas",
    "highway_mpg": 26,
    "make": "toyota",
    "model": "corolla",
    "transmission": "a",
    "year": 1993
  },
  {
    "city_mpg": 23,
    "class": "compact car",
    "combination_mpg": 26,
    "cylinders": 4,
    "displacement": 1.6,
    "drive": "fwd",
    "fuel_type": "gas",
    "highway_mpg": 31,
    "make": "toyota",
    "model": "corolla",
    "transmission": "m",
    "year": 1993
  },
  {
    "city_mpg": 23,
    "class": "compact car",
    "combination_mpg": 25,
    "cylinders": 4,
    "displacement": 1.8,
    "drive": "fwd",
    "fuel_type": "gas",
    "highway_mpg": 30,
    "make": "toyota",
    "model": "corolla",
    "transmission": "a",
    "year": 1993
  },
  {
    "city_mpg": 23,
    "class": "compact car",
    "combination_mpg": 26,
    "cylinders": 4,
    "displacement": 1.8,
    "drive": "fwd",
    "fuel_type": "gas",
    "highway_mpg": 30,
    "make": "toyota",
    "model": "corolla",
    "transmission": "m",
    "year": 1993
  },
  {
    "city_mpg": 23,
    "class": "small station wagon",
    "combination_mpg": 25,
    "cylinders": 4,
    "displacement": 1.8,
    "drive": "fwd",
    "fuel_type": "gas",
    "highway_mpg": 30,
    "make": "toyota",
    "model": "corolla wagon",
    "transmission": "a",
    "year": 1993
  }
]