"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useAuth, userContext } from '../useContext/context'
const inter = Inter({ subsets: ['latin'] })
import {contextProps, decodedUser, userTypes} from "../types"
import { useState } from 'react'
import { logoutUser } from '@/lib/actions/user.action'
import Cookies from 'js-cookie'

// export const metadata: Metadata = {
//   title: 'Car  hub',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
    const initialState:contextProps = {
      user: null,
      loading: false,
      error:null
    }
  const initialUser:decodedUser = {
    id:"",
    email:"",
    image: "",
    isBoarded:false
  }
  const data=useAuth()
  const [user,setUser]=useState(data.user)
  const loginUser = (userData: decodedUser) => {
   
    userData&&setUser({    id:userData.id,
    email:userData.email,
    image:userData.image,
    isBoarded:userData.isBoarded})
  }
  const logout = async () => {
    const userToken = Cookies.remove("userToken");
    console.log(userToken)
    await logoutUser()
  }
  
  return (
    <userContext.Provider value={{ user, loginUser,logout }}>
    <html lang="en">
      <body className='relative '>
        
        {children}
       
        </body>
      </html>
      </userContext.Provider>
  )
}
